/* This file is generated by MCB1700.bat via Rhapsody; do not edit! */ 

#define WST_RXF_V6

#define _DEBUG

#define WST_CFG_HIGHWATERMARKS





#define WST_RPY_VTBL_KIND_OXF


#define WST_MEM_NO_DEBUG


#define WST_MEM_REQUEST_ONE_POOL


#define WST_MEM_DISABLE_INTERRUPTS


#define WST_MEM_NO_STATISTICS


#define WST_MEM_NO_TAIL

#define WST_MEM_TINY_POOL_DEFINITION uint32 tinyBuffers[ WST_INITIAL_TINY_BUFFERS ] [ ( WST_TINY_BUFFER_SIZE + sizeof( WST_MEM_Block) + 3 ) / 4 ]; 
#define WST_MEM_SMALL_POOL_DEFINITION uint32 smallBuffers[ WST_INITIAL_SMALL_BUFFERS ] [ ( WST_SMALL_BUFFER_SIZE + sizeof( WST_MEM_Block) + 3 ) / 4 ]; 
#define WST_MEM_MEDIUM_POOL_DEFINITION uint32 mediumBuffers[ WST_INITIAL_MEDIUM_BUFFERS ][ ( WST_MEDIUM_BUFFER_SIZE + sizeof( WST_MEM_Block) + 3 ) / 4 ]; 
#define WST_MEM_LARGE_POOL_DEFINITION uint32 largeBuffers[ WST_INITIAL_LARGE_BUFFERS ] [ ( WST_LARGE_BUFFER_SIZE + sizeof( WST_MEM_Block) + 3 ) / 4 ]; 
#define WST_MEM_HUGE_POOL_DEFINITION uint32 hugeBuffers[ WST_INITIAL_HUGE_BUFFERS ] [ ( WST_HUGE_BUFFER_SIZE + sizeof( WST_MEM_Block) + 3 ) / 4 ]; 
